apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api-app
  namespace: argocd
spec:
  project: default
  source:
    # Update this URL with the Git repository where your k8s manifests are stored
    repoURL: 'https://github.com/lewisc99/dotnet_eks_and_argocd_simple_project.git'
    targetRevision: HEAD
    path: my-eks-argo-setup/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
