name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets  # <<< ADD THIS if you keep secrets under Environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the project
        run: dotnet build api/api.csproj --configuration Release

      - name: Publish the project
        run: dotnet publish api/api.csproj --configuration Release --output ./publish

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api:latest
